-- Idempotency keys, so a retried write cannot append a second settlement
-- event.
--
-- WHY THIS IS NOT OPTIONAL HERE. settlement_events is append only and
-- bet_state is a fold over it, which is what makes repeated partial cash
-- outs, a Rule 4 and a late promo refund all representable. The same property
-- makes a duplicated request permanent: a phone on a bad connection that
-- sends "won" twice does not overwrite a result, it appends a second one, and
-- there is no edit to undo it with. A person double tapping Record on a
-- platform lift would have settled the same bet twice and every figure
-- derived from it would have been wrong for good.
--
-- The key is generated by the client, once per intended write, and sent with
-- the request. The row is claimed inside the SAME transaction as the event
-- and the bet_state recompute, so all three commit together or none of them
-- do: a write that fails releases its key and can be retried honestly, and a
-- write that succeeded returns the state it produced rather than doing it
-- again.
--
-- Keyed by (account_id, key) rather than by the key alone. The key comes from
-- a browser, so it is not ours to trust as unique across accounts, and one
-- account must never be able to read back another's stored result by guessing
-- a UUID.
create table if not exists write_keys (
  account_id  uuid not null references accounts(id) on delete cascade,
  key         text not null,
  -- Which route claimed it. A key reused across two different operations is a
  -- client bug, and this is what lets the server say so rather than replaying
  -- the wrong answer.
  scope       text not null,
  -- What the write returned, replayed verbatim to a duplicate request.
  result      jsonb,
  created_at  timestamptz not null default now(),
  primary key (account_id, key)
);

-- Old keys are of no use: a retry arrives in seconds, not in days. The
-- retention sweep deletes them, and this is the index it deletes on.
create index if not exists write_keys_created_idx on write_keys (created_at);
