/* STRINGS.md, generated from the built page.
 *
 * WHY IT IS GENERATED. A hand-written string inventory is out of date the
 * first time somebody edits a sentence, and an inventory that is wrong is
 * worse than none: it sends whoever is reading it to change copy that no
 * longer exists. This renders the real page, walks every view in document
 * order, and writes down what is actually there.
 *
 *   node tools/strings.mjs           write STRINGS.md
 *   node tools/strings.mjs --check   fail if STRINGS.md is out of date
 *
 * The check runs in `npm run verify`, so the file cannot drift from the
 * product without the build going red.
 *
 * WHAT IT CANNOT SEE, and how that is handled. A DOM walk finds anything
 * rendered, including the states that are in the markup but hidden. It
 * cannot find a string that only exists inside a function: toasts, network
 * error messages and validation text. Those are read out of the source
 * instead, so the two halves together cover everything anybody reads.
 */
import { chromium } from 'playwright-core';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createServer } from 'node:http';
import { installStub } from './apistub.mjs';
import { BOT } from '../api/_lib/bot-strings.js';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const CHROME = process.env.CHROME_BIN || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const OUT = path.join(root, 'STRINGS.md');

/* Every view, in the order somebody meets them. The order is editorial:
   this document is read top to bottom by a person, not looked up. */
const VIEWS = [
  ['landing', 'Landing page'],
  ['demo', 'Demo page (no account needed)'],
  ['pricing', 'Pricing'],
  ['pay', 'Checkout'],
  ['setup', 'Sign up, sign in, verify and onboarding'],
  ['dash', 'Dashboard: overview, ledger, social'],
  ['imp', 'Import'],
  ['util', 'Data utilities'],
  ['settings', 'Settings'],
  ['prof', 'A Slipper profile'],
  ['books', 'Bookmaker pages'],
  ['calc', 'Calculators'],
  ['faqs', 'Reference FAQ'],
  ['soon', 'Coming soon'],
  ['log', 'Changelog'],
  ['feedback', 'Feedback'],
  ['howto', 'How it works'],
  ['help', 'Help'],
  ['terms', 'Terms of use'],
  ['privacy', 'Privacy policy']
];

const PREAMBLE = `# Slippery: every word in the product

*Generated by \`node tools/strings.mjs\`. Do not edit by hand; edit the
source and regenerate. \`npm run verify\` fails if this file is out of date.*

## What this is

Slippery is a bet slip tracker. You forward a screenshot of a bet slip to a
Telegram bot **at the moment you place the bet**, and it reads the stake,
odds, selection and bookmaker off the image, watches the game, settles the
bet against a results feed, and shows the real profit and loss on a
calendar. Groups rank friends in units rather than pounds, so a ten pound
bettor and a five hundred pound bettor sit in the same table honestly and
neither learns what the other stakes.

It is for people who already bet and want to know what their record
actually says rather than what they remember. It is not a bookmaker, takes
no bets, and never handles money.

**Four decisions are locked**, because each one cost real money or real
trust to learn:

1. **Capture at placement.** Logging at settlement is what turns a tracker
   into a highlight reel of somebody's winners. It is the only thing here
   nobody else can copy.
2. **The settlement rules.** A wrong grade is worse than no grade, so the
   engine refuses rather than guesses. Ninety minutes only, whole lines
   push, handicaps grade per bookmaker, racing is never automatic.
3. **The iOS constraints.** Every one came from a real device failure:
   16px inputs, 100svh not dvh, at most three backdrop filters, no
   localStorage.
4. **Green means profit and red means loss, always.** Semantic, never
   theme-dependent, which is why there is no green or red theme.

**Stack.** Vanilla JavaScript and CSS built by esbuild into one
self-contained \`public/index.html\`. Neon serverless Postgres, Vercel
functions, Anthropic for reading slips, Gmail SMTP for codes, and scraped
results feeds. Money is integer pence everywhere and formatted only at the
edge.

## How to read this file

Each section is one screen. Entries appear in the order they appear on the
screen. \`(hidden)\` marks a state that only shows in certain conditions:
empty states, error messages, loading text. Those are where the wording is
usually worst and hardest to find, which is why they are included.
`;

/* Which kind of thing a piece of text is. Ordered: the first match wins,
   so the specific classes have to come before the generic tags. */
const ROLE_RULES = [
  ['.eyepill', 'eyebrow pill'],
  ['.eyebrow', 'eyebrow'],
  ['.sect-badge', 'section badge'],
  ['.demotag', 'badge'],
  ['.soonbadge', 'status badge'],
  ['.logtag', 'tag'],
  ['.tagbit', 'tag'],
  ['.sect-h em', 'headline line 2 (accent colour)'],
  ['.sect-h', 'headline line 1'],
  ['.sect-lede', 'lede'],
  ['.sect-said', 'conclusion line'],
  ['.rowt', 'row title'],
  ['.rows', 'row subtitle'],
  ['.sect-ticks span', 'checkmark item'],
  ['h1', 'h1'],
  ['h2', 'h2'],
  ['h3', 'h3'],
  ['summary', 'accordion question'],
  ['.lede', 'sub'],
  ['.sell', 'sub'],
  ['.sub', 'sub'],
  ['.desc', 'description'],
  ['.stepnote', 'note'],
  ['.hinttext', 'hint'],
  ['.fineprint', 'fine print'],
  ['.formerr', 'validation message'],
  ['.emptystate .t', 'empty state title'],
  ['.emptystate p', 'empty state body'],
  ['.notice', 'notice'],
  ['.spamnote', 'note'],
  ['.linkcode', 'code'],
  ['label', 'field label'],
  ['.lab', 'field label'],
  ['button', 'button'],
  ['a', 'link'],
  ['th', 'table heading'],
  ['li', 'list item'],
  ['dt', 'term'],
  ['dd', 'value']
];

function serve(dir) {
  const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css',
    '.woff2': 'font/woff2', '.png': 'image/png', '.svg': 'image/svg+xml',
    '.webmanifest': 'application/manifest+json' };
  return new Promise(resolve => {
    const server = createServer(async (req, res) => {
      let p = decodeURIComponent(req.url.split('?')[0]);
      if (p === '/') p = '/index.html';
      try {
        const buf = await readFile(path.join(dir, p));
        res.writeHead(200, { 'content-type': MIME[path.extname(p)] || 'application/octet-stream' });
        res.end(buf);
      } catch { res.writeHead(404); res.end('not found'); }
    });
    server.listen(0, () => resolve({ server, port: server.address().port }));
  });
}

/* ---------------- the DOM half ---------------- */
async function walkView(page, id) {
  return page.evaluate(({ id, rules }) => {
    const view = document.getElementById(id);
    if (!view) return [];
    const out = [];
    const seen = new Set();

    const roleOf = el => {
      for (const [sel, role] of rules) { try { if (el.matches(sel)) return role; } catch { /* bad sel */ } }
      return 'text';
    };
    /* Only the element's OWN text, so a paragraph inside a card is not
       also reported as part of the card. */
    const ownText = el => {
      let s = '';
      for (const n of el.childNodes) if (n.nodeType === 3) s += n.nodeValue;
      return s.replace(/\s+/g, ' ').trim();
    };
    /* DATA IS NOT COPY.
       A figure read off the fabricated sample, a team name, a price or a
       date is not a string anybody edits, and 1,900 of them buried the 400
       that matter. Two filters: anything inside a container that exists to
       hold values, and anything shaped like a value. */
    const DATA_CONTAINERS = [
      '.dtable tbody', '.drow2', '.ch-row', '.demobar', '.plrow', '.dchip',
      '#previewRows', '#chromeTop', '#chromeStats', '.jk-slip', '.jk-readout',
      '.jk-cal', '.bethead', '.betrow', '.calcout', '.browserow .bname',
      '.kvline', '.reviewline', '.sliprow', '.dtile .dv', '.dtile .ds'
    ].join(',');
    const VALUE = /^[+\-\u2212]?[£$€]?[\d,]+(\.\d+)?%?$/;
    const looksLikeData = (el, text) => {
      if (el.closest(DATA_CONTAINERS)) return true;
      if (text.length < 2) return true;
      if (VALUE.test(text)) return true;
      if (/^\d{1,2}[:/.]\d{2}/.test(text)) return true;       // times and dates
      if (/^\d+W\s*[\u2013-]\s*\d+L$/.test(text)) return true;  // 12W - 8L
      if (!/[a-z]{3}/.test(text)) return true;                 // no real word in it
      return false;
    };

    const INLINE = new Set(['A', 'B', 'EM', 'I', 'STRONG', 'SMALL', 'CODE', 'U', 'SPAN']);
    const SENTENCE = new Set(['H1', 'H2', 'H3', 'P', 'LI', 'SUMMARY', 'DD', 'DT', 'LABEL', 'BUTTON']);

    const isHidden = el => {
      for (let n = el; n && n !== view; n = n.parentElement) {
        if (n.hasAttribute && n.hasAttribute('hidden')) return true;
        if (n.classList && n.classList.contains('sr')) return true;
      }
      return false;
    };

    /* A heading with a landmark under it opens a group, so the document
       reads as sections rather than as one long list. */
    for (const el of view.querySelectorAll('*')) {
      if (el.closest('script, style')) continue;
      /* Decorative subtrees are not read by anybody, including a screen
         reader, so they are illustration rather than copy. */
      if (el.closest('[aria-hidden="true"]')) continue;
      const text = ownText(el);
      const ph = el.getAttribute && el.getAttribute('placeholder');
      const hidden = isHidden(el);

      /* A SENTENCE IS ONE STRING, EVEN WITH TAGS IN IT.
         Own-text-only keeps a paragraph from being reported twice, once
         inside its card, but it also tears a sentence apart wherever the
         copy has emphasis in it: the hero h1 is one word per span, and
         "£412.60 is what memory keeps" arrived as "is what memory keeps"
         with the figure missing. When every element child is inline
         emphasis, the whole thing is taken and the children are marked
         seen so they are not repeated. */
      const kids = [...el.children];
      const allInline = kids.length > 0 && kids.every(k =>
        INLINE.has(k.tagName) || k.classList.contains('hero-word') ||
        k.classList.contains('herolink') || k.classList.contains('slipword'));
      if (allInline && SENTENCE.has(el.tagName) || (allInline && el.id === 'heroHeading')) {
        const whole = el.textContent.replace(/\s+/g, ' ').trim();
        if (whole && !looksLikeData(el, whole)) {
          const key = el.tagName + '|' + whole;
          if (!seen.has(key)) { seen.add(key); out.push({ role: roleOf(el), text: whole, hidden }); }
        }
        for (const k of el.querySelectorAll('*')) {
          seen.add(k.tagName + '|' + ownText(k));
        }
        continue;
      }

      if (text && !looksLikeData(el, text)) {
        const key = el.tagName + '|' + text;
        if (!seen.has(key)) {
          seen.add(key);
          out.push({ role: roleOf(el), text, hidden });
        }
      }
      if (ph) out.push({ role: 'placeholder', text: ph, hidden });
      /* Options inside a select are text somebody reads and chooses. */
      if (el.tagName === 'OPTION' && !text && el.textContent.trim()) {
        out.push({ role: 'option', text: el.textContent.trim(), hidden });
      }
    }
    return out;
  }, { id, rules: ROLE_RULES });
}

/* ---------------- the source half ----------------
   Toasts, network errors and validation messages only exist inside
   functions, so no amount of rendering finds them. Parsed out of the
   source instead. */
async function fromSource() {
  const files = ['main.js', 'auth.js', 'render.js', 'content.js', 'pages.js', 'demo.js', 'csv.js'];
  const toasts = new Set(), errors = new Set();
  for (const f of files) {
    let src;
    try { src = await readFile(path.join(root, 'src', 'js', f), 'utf8'); } catch { continue; }
    for (const m of src.matchAll(/\btoast\(\s*'((?:[^'\\]|\\.)+)'/g)) toasts.add(unesc(m[1]));
    for (const m of src.matchAll(/\bannounce\(\s*'((?:[^'\\]|\\.)+)'/g)) toasts.add(unesc(m[1]));
    for (const m of src.matchAll(/\bcollapse\([^,]+,\s*'((?:[^'\\]|\\.)+)'/g)) toasts.add(unesc(m[1]));
    for (const m of src.matchAll(/\bshowError\([^,]+,\s*'((?:[^'\\]|\\.)+)'/g)) errors.add(unesc(m[1]));
    /* The validation helpers return their message directly, and the
       conditions in front of them contain brackets, so anchoring on the
       start of a line and skipping an `if (...)` missed most of them: only
       fifteen of roughly forty were found. Any returned literal long
       enough to be a sentence is taken, and the sentence test below drops
       the handful that are identifiers rather than copy. */
    for (const m of src.matchAll(/return\s+'((?:[^'\\]|\\.){12,})'/g)) {
      const t = unesc(m[1]);
      if (isSentence(t)) errors.add(t);
    }
  }
  return { toasts: [...toasts].sort(), errors: [...errors].sort() };
}
/* A returned literal is copy if it reads like a sentence: more than one
   word, starting with a capital, and not a selector, a class list or a
   chunk of markup. */
const isSentence = t =>
  /\s/.test(t) && /^[A-Z£]/.test(t) && !/[<>{}]/.test(t) && !/^[A-Z-]+$/.test(t);

const unesc = s => s.replace(/\\'/g, "'").replace(/\\n/g, ' ').replace(/\\\\/g, '\\');

/* ---------------- the bot half ---------------- */
function botStrings() {
  const out = [];
  for (const [key, value] of Object.entries(BOT)) {
    if (typeof value === 'string') out.push([key, value]);
    else {
      /* A template. Called with readable placeholders so the shape of the
         sentence is visible rather than just its name. */
      const args = ['NAME', 'VALUE', 'THIRD', 'FOURTH'];
      let rendered;
      try { rendered = String(value(...args)); } catch { rendered = '(needs arguments)'; }
      out.push([key + '()', rendered]);
    }
  }
  return out;
}

/* ---------------- rendering ---------------- */
const clean = s => s.replace(/\s+/g, ' ').trim();

function section(title, rows) {
  const lines = ['## ' + title, ''];
  if (!rows.length) { lines.push('*Nothing rendered here without data.*', ''); return lines.join('\n'); }
  for (const r of rows) {
    const t = clean(r.text);
    if (!t) continue;
    lines.push('- ' + r.role + (r.hidden ? ' (hidden)' : '') + ': "' + t.replace(/"/g, '\\"') + '"');
  }
  lines.push('');
  return lines.join('\n');
}

async function build() {
  const { server, port } = await serve(path.join(root, 'public'));
  const browser = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await installStub(page);
  await page.goto('http://127.0.0.1:' + port + '/', { waitUntil: 'networkidle' });
  await page.waitForTimeout(700);

  /* Everything on at once, so lazily built lists exist and hidden states
     are in the DOM to be found. */
  await page.evaluate(() => {
    document.querySelectorAll('.view').forEach(v => v.classList.add('on'));
    const hit = s => { const e = document.querySelector(s); if (e) e.click(); };
    hit('#runToggle');
    hit('[data-pane="ledger"]');
    hit('[data-pane="social"]');
    hit('[data-social="socialBrowse"]');
  });
  await page.waitForTimeout(700);

  const parts = [PREAMBLE];
  for (const [id, title] of VIEWS) {
    parts.push(section(title, await walkView(page, id)));
  }

  const src = await fromSource();
  parts.push('## Toasts\n\n*Confirmations and one-line messages, shown briefly at the ' +
    'bottom of the screen. These only exist inside functions, so they are read ' +
    'out of the source rather than off the page.*\n');
  for (const t of src.toasts) parts.push('- "' + clean(t).replace(/"/g, '\\"') + '"');
  parts.push('');

  parts.push('## Errors and validation\n\n*What the product says when something is ' +
    'wrong or a field is not right. A line that stops mid-sentence is a ' +
    'string joined to a value at runtime, so the figure or field name that ' +
    'completes it is not in the source to quote.*\n');
  for (const t of src.errors) parts.push('- "' + clean(t).replace(/"/g, '\\"') + '"');
  parts.push('');

  parts.push('## Telegram bot\n\n*Every message the bot can send, from ' +
    '`api/_lib/bot-strings.js`. Placeholders are shown in capitals. ' +
    'Telegram markdown: `*bold*`, `_italic_`.*\n');
  for (const [key, value] of botStrings()) {
    parts.push('- `' + key + '`: "' + clean(value).replace(/"/g, '\\"') + '"');
  }
  parts.push('');

  await browser.close();
  server.close();
  return parts.join('\n');
}

const text = await build();

if (process.argv.includes('--check')) {
  let existing = '';
  try { existing = await readFile(OUT, 'utf8'); } catch { /* not written yet */ }
  if (existing.trim() !== text.trim()) {
    console.error('STRINGS.md is out of date. Run `node tools/strings.mjs` and commit the result.');
    process.exit(1);
  }
  console.log('  strings STRINGS.md matches the product');
} else {
  await writeFile(OUT, text);
  const n = text.split('\n').filter(l => l.startsWith('- ')).length;
  console.log('  strings STRINGS.md written, ' + n + ' entries');
}
